# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

In [3]:
import numpy as np
# code here (you may create an array of your own choice)
a=np.arange(1.0,10.0,0.5)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

In [6]:
# code here (you may create an array of your choice of size)
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr1=np.zeros((2,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

3.Generate an n by n identity array. The default dtype is float64.

In [10]:
# code here (you may create an array of your choice of size)
arr2=np.identity(3)
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

In [25]:
# code here (use the array createed in Question 1 for this)
np.empty(2)
b=np.full(3,5.0)
b
a.max()
a.min()
a.std()
a.mean()
a.var()
a.argmax()
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

5. Create the array below with a = np.arange(-15, 15).reshape(5, 6) ** 2

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

In [45]:
# code here and try to figure out different functions on your own (as stated in Rule 3, also figure out how to propogate missing values as stated in Rule 4)
c = np.arange(-15, 15).reshape(5, 6) ** 2
c.shape

# mean_val = np.mean(c)# Mean of the array
# mean_val
# sum_val = np.sum(c) # Sum of the array
# sum_val
# std_val = np.std(c)           # Standard deviation
# std_val
# prod_val = np.prod(c)
# prod_val
# d= c+10
# d
e=c-3
e
f=c/4
f
h=np.sqrt(c)
h
g=np.exp(c)
g

array([[5.20305514e+97, 1.32348326e+85, 2.48752493e+73, 3.45466066e+62,
        3.54513118e+52, 2.68811714e+43],
       [1.50609731e+35, 6.23514908e+27, 1.90734657e+21, 4.31123155e+15,
        7.20048993e+10, 8.88611052e+06],
       [8.10308393e+03, 5.45981500e+01, 2.71828183e+00, 1.00000000e+00,
        2.71828183e+00, 5.45981500e+01],
       [8.10308393e+03, 8.88611052e+06, 7.20048993e+10, 4.31123155e+15,
        1.90734657e+21, 6.23514908e+27],
       [1.50609731e+35, 2.68811714e+43, 3.54513118e+52, 3.45466066e+62,
        2.48752493e+73, 1.32348326e+85]])

6.Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum

In [47]:
# code here and display all 3 values appropriately. You MUST NOT choose an array of your own choice.
i= np.arange(-15, 15).reshape(5, 6) ** 2
print(i)
np.max(i,axis=1) #The maximum of each row

[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]


array([225,  81,   9,  64, 196])

In [49]:
#The mean of each column
np.mean(i,axis=0)

array([81., 76., 73., 72., 73., 76.])

In [51]:
#The position of the overall minimum
np.unravel_index(i.argmin(), i.shape)

(2, 3)

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [59]:
#code here # Create 2 arrays A and B with dim (5,4) and (5,) respectively, apply addition and subtraction.
arra = np.random.randint(1, 10, (5, 4))
arra1=np.random.randint(1, 10, (5,))
addition_result = arra + arra1[:, np.newaxis]
subtraction_result = arra - arra1[:, np.newaxis]
print(addition_result)
print(subtraction_result)

[[ 8 10  8  9]
 [12 14 14 11]
 [13 13  7 13]
 [ 3 11  8  4]
 [ 8  8  9  9]]
[[ 4  6  4  5]
 [ 2  4  4  1]
 [ 1  1 -5  1]
 [-1  7  4  0]
 [ 6  6  7  7]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [61]:
# Answer here (use both of these functions on an array of your own choice)
print(arra)
np.add.reduce(arra)

[[6 8 6 7]
 [7 9 9 6]
 [7 7 1 7]
 [1 9 6 2]
 [7 7 8 8]]


array([28, 40, 30, 30])

In [62]:
print(arra1)
np.add.reduce(arra1)

[2 5 6 2 1]


16

In [63]:
j=np.array([1,2,3,4,5])
np.add.accumulate(j)

array([ 1,  3,  6, 10, 15])

### We will work with the following array:

In [77]:
k = np.arange(25).reshape(5, 5)
k
#moving forward, you must use this array for the operations

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Use slicing only to select 3rd and last row along with 2nd and last columns

In [78]:
# Answer here
k[[2, -1], :][:, [1, -1]]

array([[11, 14],
       [21, 24]])

# Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [69]:
# Answer here
k[0:5:2, 2:4]

array([[ 2,  3],
       [12, 13],
       [22, 23]])

# Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [70]:
# Answer here
k[[1, 3, 4], 1:5:2]

array([[ 6,  8],
       [16, 18],
       [21, 23]])

# Change the values 1, 10, 19 and 22 in the array to -2

In [73]:
# Answer
k[[0, 2, 3, 4], [1, 0, 4, 2]] = -2
k


array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

# Repeat above using boolean indexing

In [75]:
# Answer here
k[k == 1] = -2
k[k  == 10] = -2
k[k  == 19] = -2
k[k  == 22] = -2
k

array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

# Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [87]:
# Answer here
k = np.arange(25).reshape(5, 5)
print(k)
# Boolean indexing for specific rows (1st, 3rd, and 4th rows)
row_mask = np.array([True, False, True, True])
print(row_mask)

# Slicing for columns (1st and 4th columns)
sub_array = k[:, [0, 3]]
print(sub_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ True False  True  True]
[[ 0  3]
 [ 5  8]
 [10 13]
 [15 18]
 [20 23]]


# Calculating the sum, min and max of all diagonal values

In [92]:
# Answer here
k+10
k.min()
k.max()

24

# Calculate the sum of differences between the 2nd row and 2nd last column

In [93]:
# Answer here
# Step 1: Extract the 2nd row (index 1)
second_row = k[1]

# Step 2: Extract the 2nd last column (index -2)
second_last_column = k[:, -2]

# Step 3: Calculate the differences
differences = second_row - second_last_column

# Step 4: Calculate the sum of differences
sum_of_differences = np.sum(differences)


# Create a new array that is the sum of even rows and odd rows

In [94]:
# Answer here
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]])

# Step 1: Extract even-indexed rows (0, 2, 4)
even_rows = arr[::2]  # This selects every 2nd row starting from index 0

# Step 2: Extract odd-indexed rows (1, 3)
odd_rows = arr[1::2]  # This selects every 2nd row starting from index 1

# Step 3: Calculate the sum of even and odd rows
sum_even_rows = np.sum(even_rows, axis=0)  # Sum along the rows
sum_odd_rows = np.sum(odd_rows, axis=0)    # Sum along the rows

# Step 4: Create a new array with the sums
new_array = np.array([sum_even_rows, sum_odd_rows])

# Display the new array
print("New array with sums of even and odd rows:\n", new_array)

New array with sums of even and odd rows:
 [[30 33 36 39 42]
 [20 22 24 26 28]]


## You are done. Good job!