In [2]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [5]:
# Answer Here
arr = np.array([[[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12]], 

                [[13, 14, 15, 16], 
                 [17, 18, 19, 20], 
                 [21, 22, 23, 24]]])

# Calculate sum of all elements
total_sum = np.sum(arr)
total_sum

300

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [14]:
# Answer Here
arr = np.random.randint(0, 10,(2, 3, 4, 5))
arr


array([[[[1, 3, 0, 1, 7],
         [0, 2, 9, 7, 1],
         [4, 7, 3, 2, 1],
         [8, 6, 8, 6, 0]],

        [[0, 5, 2, 8, 1],
         [4, 7, 7, 1, 4],
         [2, 4, 6, 7, 5],
         [8, 3, 0, 1, 4]],

        [[4, 7, 4, 0, 6],
         [3, 9, 0, 4, 5],
         [5, 2, 3, 2, 0],
         [3, 2, 1, 8, 0]]],


       [[[5, 4, 2, 4, 5],
         [2, 7, 4, 6, 9],
         [6, 8, 5, 7, 6],
         [4, 7, 1, 3, 6]],

        [[1, 9, 8, 1, 0],
         [0, 7, 2, 0, 7],
         [9, 4, 9, 8, 1],
         [7, 0, 3, 3, 3]],

        [[3, 4, 5, 7, 6],
         [4, 9, 2, 6, 2],
         [1, 1, 8, 5, 3],
         [3, 3, 2, 8, 8]]]])

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [13]:
# Answer Here
np.max(arr,axis=1)


array([[[5, 5, 8, 9, 8],
        [4, 6, 9, 8, 8],
        [6, 8, 4, 5, 8],
        [6, 9, 7, 8, 5]],

       [[8, 7, 9, 6, 3],
        [9, 5, 9, 4, 6],
        [9, 6, 8, 9, 8],
        [9, 8, 6, 9, 9]]])

# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [34]:
# Answer Here
import numpy as np

# Assuming temps is the 3D array with shape (7, 24, 60)
# Create a sample array with random temperature values for demonstration purposes
temps = np.random.rand(7, 24, 60) *54  # Random temperatures between 0 and 30 degrees

# Calculate the average temperature for each day (mean along axis 1 and 2)
av_temp = np.mean(temps, axis=(1, 2))
av_temp


array([27.47169677, 27.69176443, 26.88657044, 26.73127058, 26.59095311,
       26.25603061, 27.48320948])

Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [3]:
# Answer Here
readings = np.random.rand(4, 7, 24, 60) * 100  # Random sensor readings between 0 and 100
print(readings)
max_readings_per_sensor = np.max(readings, axis=(1, 2, 3))
max_readings_per_sensor

[[[[97.31607102 38.35922336 84.32738838 ... 41.45091867  7.32061213
    21.79128771]
   [13.55504497 68.55576799 36.25479959 ... 84.34475267 77.91075039
    72.74869502]
   [73.99207251 57.90071634 45.36722848 ... 84.20354479  3.2818028
    23.93699584]
   ...
   [84.8338388  54.00828509 63.2600405  ... 19.0962014  28.68530779
    52.93095896]
   [24.80912632 11.4158075  84.37580137 ... 17.4832577   4.05848203
    80.3038759 ]
   [ 8.56486715 59.71393882  5.03633787 ... 40.544049   73.2610094
    12.9839907 ]]

  [[87.96385234 12.4428338  46.53952528 ... 77.57355966 15.06382333
    10.11168035]
   [81.66157905 72.79424706 45.51637125 ...  5.3455367  14.30135022
    29.93719019]
   [40.35441622  9.04227175 88.94364726 ... 97.97582428 90.63077951
    71.51989174]
   ...
   [ 6.60812203 25.18443806 10.97850747 ... 53.84982004 79.51533922
    97.70276448]
   [72.32992503 59.34209855 48.59799116 ... 40.58086886 89.22147193
    22.60530982]
   [ 6.81050251 98.58488113 19.78354334 ... 54.5608

array([99.95948666, 99.98814685, 99.9878409 , 99.98825631])

# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [44]:
# Answer Here
dimensions = np.random.rand(100, 50, 3) * 100  # Random dimensions between 0 and 100

# Calculate the average length, width, and height across all objects
av_dim = np.mean(dimensions, axis=0)
av_dim

array([[46.79801246, 49.56105308, 48.96576269],
       [48.71788013, 47.36869724, 50.03086568],
       [45.4703239 , 46.00042743, 52.69229843],
       [48.94866632, 47.81757024, 48.93496634],
       [48.74216421, 47.06794935, 51.82960619],
       [45.85334421, 49.18437674, 50.18194953],
       [52.83084932, 52.09336207, 48.48038962],
       [50.03158746, 47.61956444, 48.82078496],
       [49.65592243, 50.72352098, 50.64481103],
       [51.27385077, 48.27149845, 44.89027753],
       [52.43611858, 46.90468589, 50.49666354],
       [51.1129702 , 49.44983784, 49.11435762],
       [46.05421371, 49.09322421, 49.14787717],
       [51.16259148, 50.57046128, 42.19504298],
       [50.09700393, 45.62040705, 50.44458124],
       [48.52918878, 52.90395409, 48.76309898],
       [48.99964476, 47.55543749, 52.57130305],
       [43.28753347, 46.02077523, 42.78019578],
       [51.05149441, 47.63345814, 48.5257583 ],
       [50.41794608, 51.61410899, 50.20705644],
       [46.00919527, 47.55542295, 50.506

# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [65]:
# Answer Here
import numpy as np

# Assuming data is the 3D array with shape (5, 6, 7)
# Create a sample array with random measurements for demonstration purposes
data = np.random.rand(5, 6, 7) * 100  # Random sensor readings between 0 and 100

# Initialize arrays to store the statistics for each sensor
total_measurements = data.shape[1] * data.shape[2]  # Total measurements for each sensor
average_measurements = np.mean(data, axis=(1, 2))  # Average measurement value
std_deviation = np.std(data, axis=(1, 2))           # Standard deviation of measurements
min_measurements = np.min(data, axis=(1, 2))        # Minimum measurement value
max_measurements = np.max(data, axis=(1, 2))        # Maximum measurement value

total_measurements
average_measurements
std_deviation
min_measurements


array([3.73744228, 3.58132089, 5.03189737, 1.89255058, 1.5575891 ])