In [5]:
import numpy as np

### Basic Array Creation

# Creatation of List
create List in python? # Check Type of list

In [3]:
#create list 
list=[1,2,3,4,5,6,7,8]
print("type:", type(list))


type: <class 'list'>


# Creatation of Arrays
1.Create an array containing 10 elements 

2.Checking array "TYPE"

3.Check data type of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.Total bytes in an Array

In [15]:
# Create 'int' array and repeat above mention steps 1-7
# Answer Here
#1.Create an array containing 10 elements
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#2.Checking array "TYPE"
type(a)

numpy.ndarray

In [17]:
#3.Check data type of array elements
a.dtype

dtype('int32')

In [18]:
#4.Array dim
a.ndim

1

In [19]:
#5.Array Shape
a.shape

(10,)

In [20]:
#6.Bytes per element
a.itemsize

4

In [21]:
#7.Total bytes in an Array
a.nbytes

40

In [22]:
# Create 'float' array and repeat above mention steps 1-7
#Answer Here
#1.Create an array containing 10 elements
b=np.array([1.2,0.4,9.1,8.8,5.6,7.9,8.4,2.4,6.1,0.5])
b

array([1.2, 0.4, 9.1, 8.8, 5.6, 7.9, 8.4, 2.4, 6.1, 0.5])

In [23]:
#2.Checking array "TYPE"
type(b)

numpy.ndarray

In [24]:
#3.Check data type of array elements
b.dtype

dtype('float64')

In [25]:
#4.Array dim
b.ndim

1

In [26]:
#5.Array Shape
b.shape

(10,)

In [27]:
#6.Bytes per element
b.itemsize

8

In [28]:
#7.Total bytes in an Array
b.nbytes

80

-Try to assign a float into an int32

-Use .fill function # fill has the same behavior


In [29]:
# Answer here
z=np.array([1.2,0.4,9.1,8.8,5.6,7.9,8.4,2.4,6.1,0.5])
ab=np.empty_like(z, dtype=np.int32)
ab.fill(0)
ab=z.astype(np.int32)
ab

array([1, 0, 9, 8, 5, 7, 8, 2, 6, 0])

-. Add two  arrays

-. Multiple both arrays

-.Use ** operator in array operation

-.Create array from 0.0 to 11.0

-.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

-.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [32]:
# Answer Here
#array 1
d=np.array([2,3,4,5])
#array 2
s=np.array([6,7,8,9])

In [31]:
#-. Add two arrays
d+s

array([ 8, 10, 12, 14])

In [33]:
#-. Multiple both arrays
d*s

array([12, 21, 32, 45])

In [34]:
#-.Use ** operator in array operation
d**s

array([     64,    2187,   65536, 1953125])

In [41]:
#-.Create array from 0.0 to 11.0
e=np.arange(12.0)
e

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [44]:
#-.Multiply entire array with a scalar value c = (2.0 * np.pi)
c=(2.0* np.pi)/10.0
f=c*e
f

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531, 6.91150384])

In [45]:
g=np.arange(1.0,3.0,0.5)
g

array([1. , 1.5, 2. , 2.5])

# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [46]:
# code here
#Etract array indices from 1 to 3:
h=np.array([5,6,7,8,9])
h[1:3]

array([6, 7])

In [47]:
#negtive indices
h[1:-2]

array([6, 7])

In [49]:
#3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
h[:3]

array([5, 6, 7])

In [53]:
#4. Grab last two elements
h[-2:]

array([8, 9])

In [54]:
#5. Grab every other element
h[::2]

array([5, 7, 9])

In [55]:
#6. slicing the last two elements returns the data there
h[-2:]

array([8, 9])

In [58]:
#7. Can we insert an iterable of length two? or a scalar value
i= np.array([0, 1, 2, 3, 4])
# we can insert an iterable of length two
i[-2:] = [-1, -2]
i

array([ 0,  1,  2, -1, -2])

In [59]:
# or a scalar value
i[-2:] = 99
i


array([ 0,  1,  2, 99, 99])

In [69]:
#8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.For example create a slice containing two elements of a changing b changed a! Have an experiment
k= np.array([0, 1, 2, 3, 4])
# create a slice containing two elements of a
l=k[2:4]
print(l)
l[0] = 10
print(l)
# changing b changed a!
k
np.shares_memory(k, l)

[2 3]
[10  3]


True

In [77]:
#9.extract values from row 3 to onward and from col 0, 2 and 5
m=np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29]])
n=m[3:, [0, 2, 5]]
n

array([[18, 20, 23],
       [24, 26, 29]])

In [82]:
#10.Perform some masking on a = np.arange(0,36).reshape(6,6)with mask = np.array([1, 0, 1, 0, 0, 1])
o=np.arange(0,36).reshape(6,6)


In [83]:
# manual creation of masks
mask = np.array([1, 0, 1, 0, 0, 1],dtype=bool)

In [89]:
mask_array=o[mask]
print("orignal array:\n", o)
print("mask_array:\n", mask_array)

orignal array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
mask_array:
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [30 31 32 33 34 35]]


### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [19]:
#code here
q=np.array([[10,15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65 ,70 ,75],
 [5,8,11,14,17, 20, 23, 26, 29, 32, 35, 38, 41, 44]])
#q.ndim
#q.shape
q

array([[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75],
       [ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44]])

### Now use indexing to select the 5th 7th and 11th columns

In [10]:
# code here
col=q[:,[4,6,10]]
col

array([[30, 40, 60],
       [17, 23, 35]])

### Select the 2nd row and fourth-last to second-last columns

In [11]:
# code here
q[1,-4:-1]

array([35, 38, 41])

### Select 3rd to 3rd last columns skipping every second column

In [12]:
# code here
q[:, 2:-2:2]

array([[20, 30, 40, 50, 60],
       [11, 17, 23, 29, 35]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [ ]:
# code here

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [17]:
t = [1, 2, 3, 4]
w = [2, 3, 4, 5]
zippp=zip(t,w)
print(list(zippp))
# Answer Here

[(1, 2), (2, 3), (3, 4), (4, 5)]


In [18]:
#For loop to add corresponding elements in two lists
sum_array=[]
for x, y in zip(t,w):
    sum_array.append(x+y)
print(sum_array)
    
# Answer Here

[3, 5, 7, 9]
