# Problem 1: Reshaping for Image Processing
You are working on an image processing project, and you have a grayscale image represented as a 1D NumPy array **img_data** of size **(m * n)**, where m and n are the dimensions of the image. Write a function **reshape_image(img_data, new_shape)** that takes the original image data and a tuple representing the new shape **(p, q)** of the image. Ensure that the total number of pixels remains unchanged. If it's not possible to reshape without changing the total number of pixels, return **None**.

In [1]:
import numpy as np

In [30]:
# Write your function in this cell
def reshape_image(img_data,new_shape):
    origjnal_img=img_data.size
    print("imag size:", origjnal_img)
    new_img_shape=new_shape[1]*new_shape[0]
    print("new shape size:", new_img_shape)
    if origjnal_img!= new_img_shape:
        return None
    reshape_image= img_data.reshape(new_shape)
    return reshape_image
    

In [32]:
img_data = np.arange(33)# Assuming a 3x3 image
print("Image data is:\n",img_data)
new_shape = (11,3)

result = reshape_image(img_data, new_shape)
print("Result of Reshspe image:\n",result)

Image data is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32]
imag size: 33
new shape size: 33
Result of Reshspe image:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]]


# Problem 2: Matrix Transpose
You are dealing with a dataset stored as a NumPy array **data_matrix** with dimensions **(m, n)**. Implement a function **transpose_matrix(data_matrix)** that returns the transpose of the given matrix.

In [48]:
# Write your function in this cell\
def transpose_matrix(data_matrix):
    row= len(data_matrix)
    col=len(data_matrix[0])
    transposed_matrix = []
    for j in range(col):
        new_row=[]
        for i in range(row):
            new_row.append(data_matrix[i][j])
        transposed_matrix.append(new_row)
    return transposed_matrix  # Return the transposed matrix

    


In [49]:
import numpy as np

data_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("data matrix is :",data_matrix)
transposer_matrix = transpose_matrix(data_matrix)
print(transposer_matrix)
data_matrix

data matrix is : [[1 2 3]
 [4 5 6]]
[[1, 4], [2, 5], [3, 6]]


array([[1, 2, 3],
       [4, 5, 6]])

# Problem 3: Flattening for Data Processing
You have a 2D array representing data from different sensors. Write a function **flatten_sensor_data(sensor_data)** that takes a 2D NumPy array representing the sensor readings and returns a flattened 1D array.

In [84]:
# Write your function in this cell
def flatten_sensor_data(sensor_data):
    data=sensor_data.flatten()
    print(data)
    print()
    print(data.ndim)    

In [85]:
import numpy as np

sensor_data = np.array([[10, 20, 30], [40, 50, 60]])
flattened_data = flatten_sensor_data(sensor_data)
print(flattened_data)

[10 20 30 40 50 60]

1
None


In [2]:
a= np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
#5 7 15  17
a[1:4:2,0:3:2]

array([[ 5,  7],
       [15, 17]])